export const UNIV_LOAD_REQUEST = "UNIV_LOAD_REQUEST";
export const UNIV_LOAD_SUCCESS = "UNIV_LOAD_SUCCESS";
export const UNIV_LOAD_FAIL = "UNIV_LOAD_FAIL";
export const UNIV_LOAD_RESET = "UNIV_LOAD_RESET";

export const UNIV_LOAD_SINGLE_REQUEST = "UNIV_LOAD_SINGLE_REQUEST";
export const UNIV_LOAD_SINGLE_SUCCESS = "UNIV_LOAD_SINGLE_SUCCESS";
export const UNIV_LOAD_SINGLE_FAIL = "UNIV_LOAD_SINGLE_FAIL";
export const UNIV_LOAD_SINGLE_RESET = "UNIV_LOAD_SINGLE_RESET";

export const REGISTER_UNIV_REQUEST = "REGISTER_UNIV_REQUEST";
export const REGISTER_UNIV_SUCCESS = "REGISTER_UNIV_SUCCESS";
export const REGISTER_UNIV_FAIL = "REGISTER_UNIV_FAIL";
export const REGISTER_UNIV_RESET = "REGISTER_UNIV_RESET";

export const UPDATE_UNIV_REQUEST = "UPDATE_UNIV_REQUEST";
export const UPDATE_UNIV_SUCCESS = "UPDATE_UNIV_SUCCESS";
export const UPDATE_UNIV_FAIL = "UPDATE_UNIV_FAIL";
export const UPDATE_UNIV_RESET = "UPDATE_UNIV_RESET";

export const DELETE_UNIV_REQUEST = "DELETE_UNIV_REQUEST";
export const DELETE_UNIV_SUCCESS = "DELETE_UNIV_SUCCESS";
export const DELETE_UNIV_FAIL = "DELETE_UNIV_FAIL";
export const DELETE_UNIV_RESET = "DELETE_UNIV_RESET";

export const PROGRAM_LOAD_REQUEST = "PROGRAM_LOAD_REQUEST";
export const PROGRAM_LOAD_SUCCESS = "PROGRAM_LOAD_SUCCESS";
export const PROGRAM_LOAD_FAIL = "PROGRAM_LOAD_FAIL";
export const PROGRAM_LOAD_RESET = "PROGRAM_LOAD_RESET";





